// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class BatPBDescriptorProto;
@class BatPBDescriptorProto_Builder;
@class BatPBDescriptorProto_ExtensionRange;
@class BatPBDescriptorProto_ExtensionRange_Builder;
@class BatPBEnumDescriptorProto;
@class BatPBEnumDescriptorProto_Builder;
@class BatPBEnumOptions;
@class BatPBEnumOptions_Builder;
@class BatPBEnumValueDescriptorProto;
@class BatPBEnumValueDescriptorProto_Builder;
@class BatPBEnumValueOptions;
@class BatPBEnumValueOptions_Builder;
@class BatPBFieldDescriptorProto;
@class BatPBFieldDescriptorProto_Builder;
@class BatPBFieldOptions;
@class BatPBFieldOptions_Builder;
@class BatPBFileDescriptorProto;
@class BatPBFileDescriptorProto_Builder;
@class BatPBFileDescriptorSet;
@class BatPBFileDescriptorSet_Builder;
@class BatPBFileOptions;
@class BatPBFileOptions_Builder;
@class BatPBMessageOptions;
@class BatPBMessageOptions_Builder;
@class BatPBMethodDescriptorProto;
@class BatPBMethodDescriptorProto_Builder;
@class BatPBMethodOptions;
@class BatPBMethodOptions_Builder;
@class BatPBServiceDescriptorProto;
@class BatPBServiceDescriptorProto_Builder;
@class BatPBServiceOptions;
@class BatPBServiceOptions_Builder;
@class BatPBUninterpretedOption;
@class BatPBUninterpretedOption_Builder;
@class BatPBUninterpretedOption_NamePart;
@class BatPBUninterpretedOption_NamePart_Builder;
typedef enum {
  PBFieldDescriptorProto_TypeTypeDouble = 1,
  PBFieldDescriptorProto_TypeTypeFloat = 2,
  PBFieldDescriptorProto_TypeTypeInt64 = 3,
  PBFieldDescriptorProto_TypeTypeUint64 = 4,
  PBFieldDescriptorProto_TypeTypeInt32 = 5,
  PBFieldDescriptorProto_TypeTypeFixed64 = 6,
  PBFieldDescriptorProto_TypeTypeFixed32 = 7,
  PBFieldDescriptorProto_TypeTypeBool = 8,
  PBFieldDescriptorProto_TypeTypeString = 9,
  PBFieldDescriptorProto_TypeTypeGroup = 10,
  PBFieldDescriptorProto_TypeTypeMessage = 11,
  PBFieldDescriptorProto_TypeTypeBytes = 12,
  PBFieldDescriptorProto_TypeTypeUint32 = 13,
  PBFieldDescriptorProto_TypeTypeEnum = 14,
  PBFieldDescriptorProto_TypeTypeSfixed32 = 15,
  PBFieldDescriptorProto_TypeTypeSfixed64 = 16,
  PBFieldDescriptorProto_TypeTypeSint32 = 17,
  PBFieldDescriptorProto_TypeTypeSint64 = 18,
} PBFieldDescriptorProto_Type;

BOOL PBFieldDescriptorProto_TypeIsValidValue(PBFieldDescriptorProto_Type value);

typedef enum {
  PBFieldDescriptorProto_LabelLabelOptional = 1,
  PBFieldDescriptorProto_LabelLabelRequired = 2,
  PBFieldDescriptorProto_LabelLabelRepeated = 3,
} PBFieldDescriptorProto_Label;

BOOL PBFieldDescriptorProto_LabelIsValidValue(PBFieldDescriptorProto_Label value);

typedef enum {
  PBFileOptions_OptimizeModeSpeed = 1,
  PBFileOptions_OptimizeModeCodeSize = 2,
  PBFileOptions_OptimizeModeLiteRuntime = 3,
} PBFileOptions_OptimizeMode;

BOOL PBFileOptions_OptimizeModeIsValidValue(PBFileOptions_OptimizeMode value);

typedef enum {
  PBFieldOptions_CTypeCord = 1,
  PBFieldOptions_CTypeStringPiece = 2,
} PBFieldOptions_CType;

BOOL PBFieldOptions_CTypeIsValidValue(PBFieldOptions_CType value);


@interface BatPBDescriptorRoot : NSObject {
}
+ (BatPBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(BatPBMutableExtensionRegistry*) registry;
@end

@interface BatPBFileDescriptorSet : BatPBGeneratedMessage {
@private
  NSMutableArray* mutableFileList;
}
- (NSArray*) fileList;
- (BatPBFileDescriptorProto*) fileAtIndex:(int32_t) index;

+ (BatPBFileDescriptorSet*) defaultInstance;
- (BatPBFileDescriptorSet*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBFileDescriptorSet_Builder*) builder;
+ (BatPBFileDescriptorSet_Builder*) builder;
+ (BatPBFileDescriptorSet_Builder*) builderWithPrototype:(BatPBFileDescriptorSet*) prototype;

+ (BatPBFileDescriptorSet*) parseFromData:(NSData*) data;
+ (BatPBFileDescriptorSet*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBFileDescriptorSet*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBFileDescriptorSet*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBFileDescriptorSet*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBFileDescriptorSet*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBFileDescriptorSet_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBFileDescriptorSet* result;
}

- (BatPBFileDescriptorSet*) defaultInstance;

- (BatPBFileDescriptorSet_Builder*) clear;
- (BatPBFileDescriptorSet_Builder*) clone;

- (BatPBFileDescriptorSet*) build;
- (BatPBFileDescriptorSet*) buildPartial;

- (BatPBFileDescriptorSet_Builder*) mergeFrom:(BatPBFileDescriptorSet*) other;
- (BatPBFileDescriptorSet_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBFileDescriptorSet_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (NSArray*) fileList;
- (BatPBFileDescriptorProto*) fileAtIndex:(int32_t) index;
- (BatPBFileDescriptorSet_Builder*) replaceFileAtIndex:(int32_t) index with:(BatPBFileDescriptorProto*) value;
- (BatPBFileDescriptorSet_Builder*) addFile:(BatPBFileDescriptorProto*) value;
- (BatPBFileDescriptorSet_Builder*) addAllFile:(NSArray*) values;
- (BatPBFileDescriptorSet_Builder*) clearFileList;
@end

@interface BatPBFileDescriptorProto : BatPBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasPackage_:1;
  BOOL hasOptions_:1;
  NSString* name;
  NSString* package;
  BatPBFileOptions* options;
  NSMutableArray* mutableDependencyList;
  NSMutableArray* mutableMessageTypeList;
  NSMutableArray* mutableEnumTypeList;
  NSMutableArray* mutableServiceList;
  NSMutableArray* mutableExtensionList;
}
- (BOOL) hasName;
- (BOOL) hasPackage;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* package;
@property (readonly, retain) BatPBFileOptions* options;
- (NSArray*) dependencyList;
- (NSString*) dependencyAtIndex:(int32_t) index;
- (NSArray*) messageTypeList;
- (BatPBDescriptorProto*) messageTypeAtIndex:(int32_t) index;
- (NSArray*) enumTypeList;
- (BatPBEnumDescriptorProto*) enumTypeAtIndex:(int32_t) index;
- (NSArray*) serviceList;
- (BatPBServiceDescriptorProto*) serviceAtIndex:(int32_t) index;
- (NSArray*) extensionList;
- (BatPBFieldDescriptorProto*) extensionAtIndex:(int32_t) index;

+ (BatPBFileDescriptorProto*) defaultInstance;
- (BatPBFileDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBFileDescriptorProto_Builder*) builder;
+ (BatPBFileDescriptorProto_Builder*) builder;
+ (BatPBFileDescriptorProto_Builder*) builderWithPrototype:(BatPBFileDescriptorProto*) prototype;

+ (BatPBFileDescriptorProto*) parseFromData:(NSData*) data;
+ (BatPBFileDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBFileDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBFileDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBFileDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBFileDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBFileDescriptorProto_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBFileDescriptorProto* result;
}

- (BatPBFileDescriptorProto*) defaultInstance;

- (BatPBFileDescriptorProto_Builder*) clear;
- (BatPBFileDescriptorProto_Builder*) clone;

- (BatPBFileDescriptorProto*) build;
- (BatPBFileDescriptorProto*) buildPartial;

- (BatPBFileDescriptorProto_Builder*) mergeFrom:(BatPBFileDescriptorProto*) other;
- (BatPBFileDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBFileDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (BatPBFileDescriptorProto_Builder*) setName:(NSString*) value;
- (BatPBFileDescriptorProto_Builder*) clearName;

- (BOOL) hasPackage;
- (NSString*) package;
- (BatPBFileDescriptorProto_Builder*) setPackage:(NSString*) value;
- (BatPBFileDescriptorProto_Builder*) clearPackage;

- (NSArray*) dependencyList;
- (NSString*) dependencyAtIndex:(int32_t) index;
- (BatPBFileDescriptorProto_Builder*) replaceDependencyAtIndex:(int32_t) index with:(NSString*) value;
- (BatPBFileDescriptorProto_Builder*) addDependency:(NSString*) value;
- (BatPBFileDescriptorProto_Builder*) addAllDependency:(NSArray*) values;
- (BatPBFileDescriptorProto_Builder*) clearDependencyList;

- (NSArray*) messageTypeList;
- (BatPBDescriptorProto*) messageTypeAtIndex:(int32_t) index;
- (BatPBFileDescriptorProto_Builder*) replaceMessageTypeAtIndex:(int32_t) index with:(BatPBDescriptorProto*) value;
- (BatPBFileDescriptorProto_Builder*) addMessageType:(BatPBDescriptorProto*) value;
- (BatPBFileDescriptorProto_Builder*) addAllMessageType:(NSArray*) values;
- (BatPBFileDescriptorProto_Builder*) clearMessageTypeList;

- (NSArray*) enumTypeList;
- (BatPBEnumDescriptorProto*) enumTypeAtIndex:(int32_t) index;
- (BatPBFileDescriptorProto_Builder*) replaceEnumTypeAtIndex:(int32_t) index with:(BatPBEnumDescriptorProto*) value;
- (BatPBFileDescriptorProto_Builder*) addEnumType:(BatPBEnumDescriptorProto*) value;
- (BatPBFileDescriptorProto_Builder*) addAllEnumType:(NSArray*) values;
- (BatPBFileDescriptorProto_Builder*) clearEnumTypeList;

- (NSArray*) serviceList;
- (BatPBServiceDescriptorProto*) serviceAtIndex:(int32_t) index;
- (BatPBFileDescriptorProto_Builder*) replaceServiceAtIndex:(int32_t) index with:(BatPBServiceDescriptorProto*) value;
- (BatPBFileDescriptorProto_Builder*) addService:(BatPBServiceDescriptorProto*) value;
- (BatPBFileDescriptorProto_Builder*) addAllService:(NSArray*) values;
- (BatPBFileDescriptorProto_Builder*) clearServiceList;

- (NSArray*) extensionList;
- (BatPBFieldDescriptorProto*) extensionAtIndex:(int32_t) index;
- (BatPBFileDescriptorProto_Builder*) replaceExtensionAtIndex:(int32_t) index with:(BatPBFieldDescriptorProto*) value;
- (BatPBFileDescriptorProto_Builder*) addExtension:(BatPBFieldDescriptorProto*) value;
- (BatPBFileDescriptorProto_Builder*) addAllExtension:(NSArray*) values;
- (BatPBFileDescriptorProto_Builder*) clearExtensionList;

- (BOOL) hasOptions;
- (BatPBFileOptions*) options;
- (BatPBFileDescriptorProto_Builder*) setOptions:(BatPBFileOptions*) value;
- (BatPBFileDescriptorProto_Builder*) setOptionsBuilder:(BatPBFileOptions_Builder*) builderForValue;
- (BatPBFileDescriptorProto_Builder*) mergeOptions:(BatPBFileOptions*) value;
- (BatPBFileDescriptorProto_Builder*) clearOptions;
@end

@interface BatPBDescriptorProto : BatPBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  NSString* name;
  BatPBMessageOptions* options;
  NSMutableArray* mutableFieldList;
  NSMutableArray* mutableExtensionList;
  NSMutableArray* mutableNestedTypeList;
  NSMutableArray* mutableEnumTypeList;
  NSMutableArray* mutableExtensionRangeList;
}
- (BOOL) hasName;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) BatPBMessageOptions* options;
- (NSArray*) fieldList;
- (BatPBFieldDescriptorProto*) fieldAtIndex:(int32_t) index;
- (NSArray*) extensionList;
- (BatPBFieldDescriptorProto*) extensionAtIndex:(int32_t) index;
- (NSArray*) nestedTypeList;
- (BatPBDescriptorProto*) nestedTypeAtIndex:(int32_t) index;
- (NSArray*) enumTypeList;
- (BatPBEnumDescriptorProto*) enumTypeAtIndex:(int32_t) index;
- (NSArray*) extensionRangeList;
- (BatPBDescriptorProto_ExtensionRange*) extensionRangeAtIndex:(int32_t) index;

+ (BatPBDescriptorProto*) defaultInstance;
- (BatPBDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBDescriptorProto_Builder*) builder;
+ (BatPBDescriptorProto_Builder*) builder;
+ (BatPBDescriptorProto_Builder*) builderWithPrototype:(BatPBDescriptorProto*) prototype;

+ (BatPBDescriptorProto*) parseFromData:(NSData*) data;
+ (BatPBDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBDescriptorProto_ExtensionRange : BatPBGeneratedMessage {
@private
  BOOL hasStart_:1;
  BOOL hasEnd_:1;
  int32_t start;
  int32_t end;
}
- (BOOL) hasStart;
- (BOOL) hasEnd;
@property (readonly) int32_t start;
@property (readonly) int32_t end;

+ (BatPBDescriptorProto_ExtensionRange*) defaultInstance;
- (BatPBDescriptorProto_ExtensionRange*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBDescriptorProto_ExtensionRange_Builder*) builder;
+ (BatPBDescriptorProto_ExtensionRange_Builder*) builder;
+ (BatPBDescriptorProto_ExtensionRange_Builder*) builderWithPrototype:(BatPBDescriptorProto_ExtensionRange*) prototype;

+ (BatPBDescriptorProto_ExtensionRange*) parseFromData:(NSData*) data;
+ (BatPBDescriptorProto_ExtensionRange*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBDescriptorProto_ExtensionRange*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBDescriptorProto_ExtensionRange*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBDescriptorProto_ExtensionRange*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBDescriptorProto_ExtensionRange*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBDescriptorProto_ExtensionRange_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBDescriptorProto_ExtensionRange* result;
}

- (BatPBDescriptorProto_ExtensionRange*) defaultInstance;

- (BatPBDescriptorProto_ExtensionRange_Builder*) clear;
- (BatPBDescriptorProto_ExtensionRange_Builder*) clone;

- (BatPBDescriptorProto_ExtensionRange*) build;
- (BatPBDescriptorProto_ExtensionRange*) buildPartial;

- (BatPBDescriptorProto_ExtensionRange_Builder*) mergeFrom:(BatPBDescriptorProto_ExtensionRange*) other;
- (BatPBDescriptorProto_ExtensionRange_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBDescriptorProto_ExtensionRange_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStart;
- (int32_t) start;
- (BatPBDescriptorProto_ExtensionRange_Builder*) setStart:(int32_t) value;
- (BatPBDescriptorProto_ExtensionRange_Builder*) clearStart;

- (BOOL) hasEnd;
- (int32_t) end;
- (BatPBDescriptorProto_ExtensionRange_Builder*) setEnd:(int32_t) value;
- (BatPBDescriptorProto_ExtensionRange_Builder*) clearEnd;
@end

@interface BatPBDescriptorProto_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBDescriptorProto* result;
}

- (BatPBDescriptorProto*) defaultInstance;

- (BatPBDescriptorProto_Builder*) clear;
- (BatPBDescriptorProto_Builder*) clone;

- (BatPBDescriptorProto*) build;
- (BatPBDescriptorProto*) buildPartial;

- (BatPBDescriptorProto_Builder*) mergeFrom:(BatPBDescriptorProto*) other;
- (BatPBDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (BatPBDescriptorProto_Builder*) setName:(NSString*) value;
- (BatPBDescriptorProto_Builder*) clearName;

- (NSArray*) fieldList;
- (BatPBFieldDescriptorProto*) fieldAtIndex:(int32_t) index;
- (BatPBDescriptorProto_Builder*) replaceFieldAtIndex:(int32_t) index with:(BatPBFieldDescriptorProto*) value;
- (BatPBDescriptorProto_Builder*) addField:(BatPBFieldDescriptorProto*) value;
- (BatPBDescriptorProto_Builder*) addAllField:(NSArray*) values;
- (BatPBDescriptorProto_Builder*) clearFieldList;

- (NSArray*) extensionList;
- (BatPBFieldDescriptorProto*) extensionAtIndex:(int32_t) index;
- (BatPBDescriptorProto_Builder*) replaceExtensionAtIndex:(int32_t) index with:(BatPBFieldDescriptorProto*) value;
- (BatPBDescriptorProto_Builder*) addExtension:(BatPBFieldDescriptorProto*) value;
- (BatPBDescriptorProto_Builder*) addAllExtension:(NSArray*) values;
- (BatPBDescriptorProto_Builder*) clearExtensionList;

- (NSArray*) nestedTypeList;
- (BatPBDescriptorProto*) nestedTypeAtIndex:(int32_t) index;
- (BatPBDescriptorProto_Builder*) replaceNestedTypeAtIndex:(int32_t) index with:(BatPBDescriptorProto*) value;
- (BatPBDescriptorProto_Builder*) addNestedType:(BatPBDescriptorProto*) value;
- (BatPBDescriptorProto_Builder*) addAllNestedType:(NSArray*) values;
- (BatPBDescriptorProto_Builder*) clearNestedTypeList;

- (NSArray*) enumTypeList;
- (BatPBEnumDescriptorProto*) enumTypeAtIndex:(int32_t) index;
- (BatPBDescriptorProto_Builder*) replaceEnumTypeAtIndex:(int32_t) index with:(BatPBEnumDescriptorProto*) value;
- (BatPBDescriptorProto_Builder*) addEnumType:(BatPBEnumDescriptorProto*) value;
- (BatPBDescriptorProto_Builder*) addAllEnumType:(NSArray*) values;
- (BatPBDescriptorProto_Builder*) clearEnumTypeList;

- (NSArray*) extensionRangeList;
- (BatPBDescriptorProto_ExtensionRange*) extensionRangeAtIndex:(int32_t) index;
- (BatPBDescriptorProto_Builder*) replaceExtensionRangeAtIndex:(int32_t) index with:(BatPBDescriptorProto_ExtensionRange*) value;
- (BatPBDescriptorProto_Builder*) addExtensionRange:(BatPBDescriptorProto_ExtensionRange*) value;
- (BatPBDescriptorProto_Builder*) addAllExtensionRange:(NSArray*) values;
- (BatPBDescriptorProto_Builder*) clearExtensionRangeList;

- (BOOL) hasOptions;
- (BatPBMessageOptions*) options;
- (BatPBDescriptorProto_Builder*) setOptions:(BatPBMessageOptions*) value;
- (BatPBDescriptorProto_Builder*) setOptionsBuilder:(BatPBMessageOptions_Builder*) builderForValue;
- (BatPBDescriptorProto_Builder*) mergeOptions:(BatPBMessageOptions*) value;
- (BatPBDescriptorProto_Builder*) clearOptions;
@end

@interface BatPBFieldDescriptorProto : BatPBGeneratedMessage {
@private
  BOOL hasNumber_:1;
  BOOL hasName_:1;
  BOOL hasTypeName_:1;
  BOOL hasExtendee_:1;
  BOOL hasDefaultValue_:1;
  BOOL hasOptions_:1;
  BOOL hasLabel_:1;
  BOOL hasType_:1;
  int32_t number;
  NSString* name;
  NSString* typeName;
  NSString* extendee;
  NSString* defaultValue;
  BatPBFieldOptions* options;
  PBFieldDescriptorProto_Label label;
  PBFieldDescriptorProto_Type type;
}
- (BOOL) hasName;
- (BOOL) hasNumber;
- (BOOL) hasLabel;
- (BOOL) hasType;
- (BOOL) hasTypeName;
- (BOOL) hasExtendee;
- (BOOL) hasDefaultValue;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t number;
@property (readonly) PBFieldDescriptorProto_Label label;
@property (readonly) PBFieldDescriptorProto_Type type;
@property (readonly, retain) NSString* typeName;
@property (readonly, retain) NSString* extendee;
@property (readonly, retain) NSString* defaultValue;
@property (readonly, retain) BatPBFieldOptions* options;

+ (BatPBFieldDescriptorProto*) defaultInstance;
- (BatPBFieldDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBFieldDescriptorProto_Builder*) builder;
+ (BatPBFieldDescriptorProto_Builder*) builder;
+ (BatPBFieldDescriptorProto_Builder*) builderWithPrototype:(BatPBFieldDescriptorProto*) prototype;

+ (BatPBFieldDescriptorProto*) parseFromData:(NSData*) data;
+ (BatPBFieldDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBFieldDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBFieldDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBFieldDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBFieldDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBFieldDescriptorProto_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBFieldDescriptorProto* result;
}

- (BatPBFieldDescriptorProto*) defaultInstance;

- (BatPBFieldDescriptorProto_Builder*) clear;
- (BatPBFieldDescriptorProto_Builder*) clone;

- (BatPBFieldDescriptorProto*) build;
- (BatPBFieldDescriptorProto*) buildPartial;

- (BatPBFieldDescriptorProto_Builder*) mergeFrom:(BatPBFieldDescriptorProto*) other;
- (BatPBFieldDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBFieldDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (BatPBFieldDescriptorProto_Builder*) setName:(NSString*) value;
- (BatPBFieldDescriptorProto_Builder*) clearName;

- (BOOL) hasNumber;
- (int32_t) number;
- (BatPBFieldDescriptorProto_Builder*) setNumber:(int32_t) value;
- (BatPBFieldDescriptorProto_Builder*) clearNumber;

- (BOOL) hasLabel;
- (PBFieldDescriptorProto_Label) label;
- (BatPBFieldDescriptorProto_Builder*) setLabel:(PBFieldDescriptorProto_Label) value;
- (BatPBFieldDescriptorProto_Builder*) clearLabel;

- (BOOL) hasType;
- (PBFieldDescriptorProto_Type) type;
- (BatPBFieldDescriptorProto_Builder*) setType:(PBFieldDescriptorProto_Type) value;
- (BatPBFieldDescriptorProto_Builder*) clearType;

- (BOOL) hasTypeName;
- (NSString*) typeName;
- (BatPBFieldDescriptorProto_Builder*) setTypeName:(NSString*) value;
- (BatPBFieldDescriptorProto_Builder*) clearTypeName;

- (BOOL) hasExtendee;
- (NSString*) extendee;
- (BatPBFieldDescriptorProto_Builder*) setExtendee:(NSString*) value;
- (BatPBFieldDescriptorProto_Builder*) clearExtendee;

- (BOOL) hasDefaultValue;
- (NSString*) defaultValue;
- (BatPBFieldDescriptorProto_Builder*) setDefaultValue:(NSString*) value;
- (BatPBFieldDescriptorProto_Builder*) clearDefaultValue;

- (BOOL) hasOptions;
- (BatPBFieldOptions*) options;
- (BatPBFieldDescriptorProto_Builder*) setOptions:(BatPBFieldOptions*) value;
- (BatPBFieldDescriptorProto_Builder*) setOptionsBuilder:(BatPBFieldOptions_Builder*) builderForValue;
- (BatPBFieldDescriptorProto_Builder*) mergeOptions:(BatPBFieldOptions*) value;
- (BatPBFieldDescriptorProto_Builder*) clearOptions;
@end

@interface BatPBEnumDescriptorProto : BatPBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  NSString* name;
  BatPBEnumOptions* options;
  NSMutableArray* mutableValueList;
}
- (BOOL) hasName;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) BatPBEnumOptions* options;
- (NSArray*) valueList;
- (BatPBEnumValueDescriptorProto*) valueAtIndex:(int32_t) index;

+ (BatPBEnumDescriptorProto*) defaultInstance;
- (BatPBEnumDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBEnumDescriptorProto_Builder*) builder;
+ (BatPBEnumDescriptorProto_Builder*) builder;
+ (BatPBEnumDescriptorProto_Builder*) builderWithPrototype:(BatPBEnumDescriptorProto*) prototype;

+ (BatPBEnumDescriptorProto*) parseFromData:(NSData*) data;
+ (BatPBEnumDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBEnumDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBEnumDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBEnumDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBEnumDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBEnumDescriptorProto_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBEnumDescriptorProto* result;
}

- (BatPBEnumDescriptorProto*) defaultInstance;

- (BatPBEnumDescriptorProto_Builder*) clear;
- (BatPBEnumDescriptorProto_Builder*) clone;

- (BatPBEnumDescriptorProto*) build;
- (BatPBEnumDescriptorProto*) buildPartial;

- (BatPBEnumDescriptorProto_Builder*) mergeFrom:(BatPBEnumDescriptorProto*) other;
- (BatPBEnumDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBEnumDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (BatPBEnumDescriptorProto_Builder*) setName:(NSString*) value;
- (BatPBEnumDescriptorProto_Builder*) clearName;

- (NSArray*) valueList;
- (BatPBEnumValueDescriptorProto*) valueAtIndex:(int32_t) index;
- (BatPBEnumDescriptorProto_Builder*) replaceValueAtIndex:(int32_t) index with:(BatPBEnumValueDescriptorProto*) value;
- (BatPBEnumDescriptorProto_Builder*) addValue:(BatPBEnumValueDescriptorProto*) value;
- (BatPBEnumDescriptorProto_Builder*) addAllValue:(NSArray*) values;
- (BatPBEnumDescriptorProto_Builder*) clearValueList;

- (BOOL) hasOptions;
- (BatPBEnumOptions*) options;
- (BatPBEnumDescriptorProto_Builder*) setOptions:(BatPBEnumOptions*) value;
- (BatPBEnumDescriptorProto_Builder*) setOptionsBuilder:(BatPBEnumOptions_Builder*) builderForValue;
- (BatPBEnumDescriptorProto_Builder*) mergeOptions:(BatPBEnumOptions*) value;
- (BatPBEnumDescriptorProto_Builder*) clearOptions;
@end

@interface BatPBEnumValueDescriptorProto : BatPBGeneratedMessage {
@private
  BOOL hasNumber_:1;
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  int32_t number;
  NSString* name;
  BatPBEnumValueOptions* options;
}
- (BOOL) hasName;
- (BOOL) hasNumber;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly) int32_t number;
@property (readonly, retain) BatPBEnumValueOptions* options;

+ (BatPBEnumValueDescriptorProto*) defaultInstance;
- (BatPBEnumValueDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBEnumValueDescriptorProto_Builder*) builder;
+ (BatPBEnumValueDescriptorProto_Builder*) builder;
+ (BatPBEnumValueDescriptorProto_Builder*) builderWithPrototype:(BatPBEnumValueDescriptorProto*) prototype;

+ (BatPBEnumValueDescriptorProto*) parseFromData:(NSData*) data;
+ (BatPBEnumValueDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBEnumValueDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBEnumValueDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBEnumValueDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBEnumValueDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBEnumValueDescriptorProto_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBEnumValueDescriptorProto* result;
}

- (BatPBEnumValueDescriptorProto*) defaultInstance;

- (BatPBEnumValueDescriptorProto_Builder*) clear;
- (BatPBEnumValueDescriptorProto_Builder*) clone;

- (BatPBEnumValueDescriptorProto*) build;
- (BatPBEnumValueDescriptorProto*) buildPartial;

- (BatPBEnumValueDescriptorProto_Builder*) mergeFrom:(BatPBEnumValueDescriptorProto*) other;
- (BatPBEnumValueDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBEnumValueDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (BatPBEnumValueDescriptorProto_Builder*) setName:(NSString*) value;
- (BatPBEnumValueDescriptorProto_Builder*) clearName;

- (BOOL) hasNumber;
- (int32_t) number;
- (BatPBEnumValueDescriptorProto_Builder*) setNumber:(int32_t) value;
- (BatPBEnumValueDescriptorProto_Builder*) clearNumber;

- (BOOL) hasOptions;
- (BatPBEnumValueOptions*) options;
- (BatPBEnumValueDescriptorProto_Builder*) setOptions:(BatPBEnumValueOptions*) value;
- (BatPBEnumValueDescriptorProto_Builder*) setOptionsBuilder:(BatPBEnumValueOptions_Builder*) builderForValue;
- (BatPBEnumValueDescriptorProto_Builder*) mergeOptions:(BatPBEnumValueOptions*) value;
- (BatPBEnumValueDescriptorProto_Builder*) clearOptions;
@end

@interface BatPBServiceDescriptorProto : BatPBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasOptions_:1;
  NSString* name;
  BatPBServiceOptions* options;
  NSMutableArray* mutableMethodList;
}
- (BOOL) hasName;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) BatPBServiceOptions* options;
- (NSArray*) methodList;
- (BatPBMethodDescriptorProto*) methodAtIndex:(int32_t) index;

+ (BatPBServiceDescriptorProto*) defaultInstance;
- (BatPBServiceDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBServiceDescriptorProto_Builder*) builder;
+ (BatPBServiceDescriptorProto_Builder*) builder;
+ (BatPBServiceDescriptorProto_Builder*) builderWithPrototype:(BatPBServiceDescriptorProto*) prototype;

+ (BatPBServiceDescriptorProto*) parseFromData:(NSData*) data;
+ (BatPBServiceDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBServiceDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBServiceDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBServiceDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBServiceDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBServiceDescriptorProto_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBServiceDescriptorProto* result;
}

- (BatPBServiceDescriptorProto*) defaultInstance;

- (BatPBServiceDescriptorProto_Builder*) clear;
- (BatPBServiceDescriptorProto_Builder*) clone;

- (BatPBServiceDescriptorProto*) build;
- (BatPBServiceDescriptorProto*) buildPartial;

- (BatPBServiceDescriptorProto_Builder*) mergeFrom:(BatPBServiceDescriptorProto*) other;
- (BatPBServiceDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBServiceDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (BatPBServiceDescriptorProto_Builder*) setName:(NSString*) value;
- (BatPBServiceDescriptorProto_Builder*) clearName;

- (NSArray*) methodList;
- (BatPBMethodDescriptorProto*) methodAtIndex:(int32_t) index;
- (BatPBServiceDescriptorProto_Builder*) replaceMethodAtIndex:(int32_t) index with:(BatPBMethodDescriptorProto*) value;
- (BatPBServiceDescriptorProto_Builder*) addMethod:(BatPBMethodDescriptorProto*) value;
- (BatPBServiceDescriptorProto_Builder*) addAllMethod:(NSArray*) values;
- (BatPBServiceDescriptorProto_Builder*) clearMethodList;

- (BOOL) hasOptions;
- (BatPBServiceOptions*) options;
- (BatPBServiceDescriptorProto_Builder*) setOptions:(BatPBServiceOptions*) value;
- (BatPBServiceDescriptorProto_Builder*) setOptionsBuilder:(BatPBServiceOptions_Builder*) builderForValue;
- (BatPBServiceDescriptorProto_Builder*) mergeOptions:(BatPBServiceOptions*) value;
- (BatPBServiceDescriptorProto_Builder*) clearOptions;
@end

@interface BatPBMethodDescriptorProto : BatPBGeneratedMessage {
@private
  BOOL hasName_:1;
  BOOL hasInputType_:1;
  BOOL hasOutputType_:1;
  BOOL hasOptions_:1;
  NSString* name;
  NSString* inputType;
  NSString* outputType;
  BatPBMethodOptions* options;
}
- (BOOL) hasName;
- (BOOL) hasInputType;
- (BOOL) hasOutputType;
- (BOOL) hasOptions;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* inputType;
@property (readonly, retain) NSString* outputType;
@property (readonly, retain) BatPBMethodOptions* options;

+ (BatPBMethodDescriptorProto*) defaultInstance;
- (BatPBMethodDescriptorProto*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBMethodDescriptorProto_Builder*) builder;
+ (BatPBMethodDescriptorProto_Builder*) builder;
+ (BatPBMethodDescriptorProto_Builder*) builderWithPrototype:(BatPBMethodDescriptorProto*) prototype;

+ (BatPBMethodDescriptorProto*) parseFromData:(NSData*) data;
+ (BatPBMethodDescriptorProto*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBMethodDescriptorProto*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBMethodDescriptorProto*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBMethodDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBMethodDescriptorProto*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBMethodDescriptorProto_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBMethodDescriptorProto* result;
}

- (BatPBMethodDescriptorProto*) defaultInstance;

- (BatPBMethodDescriptorProto_Builder*) clear;
- (BatPBMethodDescriptorProto_Builder*) clone;

- (BatPBMethodDescriptorProto*) build;
- (BatPBMethodDescriptorProto*) buildPartial;

- (BatPBMethodDescriptorProto_Builder*) mergeFrom:(BatPBMethodDescriptorProto*) other;
- (BatPBMethodDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBMethodDescriptorProto_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (BatPBMethodDescriptorProto_Builder*) setName:(NSString*) value;
- (BatPBMethodDescriptorProto_Builder*) clearName;

- (BOOL) hasInputType;
- (NSString*) inputType;
- (BatPBMethodDescriptorProto_Builder*) setInputType:(NSString*) value;
- (BatPBMethodDescriptorProto_Builder*) clearInputType;

- (BOOL) hasOutputType;
- (NSString*) outputType;
- (BatPBMethodDescriptorProto_Builder*) setOutputType:(NSString*) value;
- (BatPBMethodDescriptorProto_Builder*) clearOutputType;

- (BOOL) hasOptions;
- (BatPBMethodOptions*) options;
- (BatPBMethodDescriptorProto_Builder*) setOptions:(BatPBMethodOptions*) value;
- (BatPBMethodDescriptorProto_Builder*) setOptionsBuilder:(BatPBMethodOptions_Builder*) builderForValue;
- (BatPBMethodDescriptorProto_Builder*) mergeOptions:(BatPBMethodOptions*) value;
- (BatPBMethodDescriptorProto_Builder*) clearOptions;
@end

@interface BatPBFileOptions : BatPBExtendableMessage {
@private
  BOOL hasJavaMultipleFiles_:1;
  BOOL hasJavaPackage_:1;
  BOOL hasJavaOuterClassname_:1;
  BOOL hasOptimizeFor_:1;
  BOOL javaMultipleFiles_:1;
  NSString* javaPackage;
  NSString* javaOuterClassname;
  PBFileOptions_OptimizeMode optimizeFor;
  NSMutableArray* mutableUninterpretedOptionList;
}
- (BOOL) hasJavaPackage;
- (BOOL) hasJavaOuterClassname;
- (BOOL) hasJavaMultipleFiles;
- (BOOL) hasOptimizeFor;
@property (readonly, retain) NSString* javaPackage;
@property (readonly, retain) NSString* javaOuterClassname;
- (BOOL) javaMultipleFiles;
@property (readonly) PBFileOptions_OptimizeMode optimizeFor;
- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (BatPBFileOptions*) defaultInstance;
- (BatPBFileOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBFileOptions_Builder*) builder;
+ (BatPBFileOptions_Builder*) builder;
+ (BatPBFileOptions_Builder*) builderWithPrototype:(BatPBFileOptions*) prototype;

+ (BatPBFileOptions*) parseFromData:(NSData*) data;
+ (BatPBFileOptions*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBFileOptions*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBFileOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBFileOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBFileOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBFileOptions_Builder : BatPBExtendableMessage_Builder {
@private
  BatPBFileOptions* result;
}

- (BatPBFileOptions*) defaultInstance;

- (BatPBFileOptions_Builder*) clear;
- (BatPBFileOptions_Builder*) clone;

- (BatPBFileOptions*) build;
- (BatPBFileOptions*) buildPartial;

- (BatPBFileOptions_Builder*) mergeFrom:(BatPBFileOptions*) other;
- (BatPBFileOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBFileOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasJavaPackage;
- (NSString*) javaPackage;
- (BatPBFileOptions_Builder*) setJavaPackage:(NSString*) value;
- (BatPBFileOptions_Builder*) clearJavaPackage;

- (BOOL) hasJavaOuterClassname;
- (NSString*) javaOuterClassname;
- (BatPBFileOptions_Builder*) setJavaOuterClassname:(NSString*) value;
- (BatPBFileOptions_Builder*) clearJavaOuterClassname;

- (BOOL) hasJavaMultipleFiles;
- (BOOL) javaMultipleFiles;
- (BatPBFileOptions_Builder*) setJavaMultipleFiles:(BOOL) value;
- (BatPBFileOptions_Builder*) clearJavaMultipleFiles;

- (BOOL) hasOptimizeFor;
- (PBFileOptions_OptimizeMode) optimizeFor;
- (BatPBFileOptions_Builder*) setOptimizeFor:(PBFileOptions_OptimizeMode) value;
- (BatPBFileOptions_Builder*) clearOptimizeFor;

- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (BatPBFileOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(BatPBUninterpretedOption*) value;
- (BatPBFileOptions_Builder*) addUninterpretedOption:(BatPBUninterpretedOption*) value;
- (BatPBFileOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (BatPBFileOptions_Builder*) clearUninterpretedOptionList;
@end

@interface BatPBMessageOptions : BatPBExtendableMessage {
@private
  BOOL hasMessageSetWireFormat_:1;
  BOOL hasNoStandardDescriptorAccessor_:1;
  BOOL messageSetWireFormat_:1;
  BOOL noStandardDescriptorAccessor_:1;
  NSMutableArray* mutableUninterpretedOptionList;
}
- (BOOL) hasMessageSetWireFormat;
- (BOOL) hasNoStandardDescriptorAccessor;
- (BOOL) messageSetWireFormat;
- (BOOL) noStandardDescriptorAccessor;
- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (BatPBMessageOptions*) defaultInstance;
- (BatPBMessageOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBMessageOptions_Builder*) builder;
+ (BatPBMessageOptions_Builder*) builder;
+ (BatPBMessageOptions_Builder*) builderWithPrototype:(BatPBMessageOptions*) prototype;

+ (BatPBMessageOptions*) parseFromData:(NSData*) data;
+ (BatPBMessageOptions*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBMessageOptions*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBMessageOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBMessageOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBMessageOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBMessageOptions_Builder : BatPBExtendableMessage_Builder {
@private
  BatPBMessageOptions* result;
}

- (BatPBMessageOptions*) defaultInstance;

- (BatPBMessageOptions_Builder*) clear;
- (BatPBMessageOptions_Builder*) clone;

- (BatPBMessageOptions*) build;
- (BatPBMessageOptions*) buildPartial;

- (BatPBMessageOptions_Builder*) mergeFrom:(BatPBMessageOptions*) other;
- (BatPBMessageOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBMessageOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMessageSetWireFormat;
- (BOOL) messageSetWireFormat;
- (BatPBMessageOptions_Builder*) setMessageSetWireFormat:(BOOL) value;
- (BatPBMessageOptions_Builder*) clearMessageSetWireFormat;

- (BOOL) hasNoStandardDescriptorAccessor;
- (BOOL) noStandardDescriptorAccessor;
- (BatPBMessageOptions_Builder*) setNoStandardDescriptorAccessor:(BOOL) value;
- (BatPBMessageOptions_Builder*) clearNoStandardDescriptorAccessor;

- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (BatPBMessageOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(BatPBUninterpretedOption*) value;
- (BatPBMessageOptions_Builder*) addUninterpretedOption:(BatPBUninterpretedOption*) value;
- (BatPBMessageOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (BatPBMessageOptions_Builder*) clearUninterpretedOptionList;
@end

@interface BatPBFieldOptions : BatPBExtendableMessage {
@private
  BOOL hasPacked_:1;
  BOOL hasDeprecated_:1;
  BOOL hasExperimentalMapKey_:1;
  BOOL hasCtype_:1;
  BOOL packed_:1;
  BOOL deprecated_:1;
  NSString* experimentalMapKey;
  PBFieldOptions_CType ctype;
  NSMutableArray* mutableUninterpretedOptionList;
}
- (BOOL) hasCtype;
- (BOOL) hasPacked;
- (BOOL) hasDeprecated;
- (BOOL) hasExperimentalMapKey;
@property (readonly) PBFieldOptions_CType ctype;
- (BOOL) packed;
- (BOOL) deprecated;
@property (readonly, retain) NSString* experimentalMapKey;
- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (BatPBFieldOptions*) defaultInstance;
- (BatPBFieldOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBFieldOptions_Builder*) builder;
+ (BatPBFieldOptions_Builder*) builder;
+ (BatPBFieldOptions_Builder*) builderWithPrototype:(BatPBFieldOptions*) prototype;

+ (BatPBFieldOptions*) parseFromData:(NSData*) data;
+ (BatPBFieldOptions*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBFieldOptions*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBFieldOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBFieldOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBFieldOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBFieldOptions_Builder : BatPBExtendableMessage_Builder {
@private
  BatPBFieldOptions* result;
}

- (BatPBFieldOptions*) defaultInstance;

- (BatPBFieldOptions_Builder*) clear;
- (BatPBFieldOptions_Builder*) clone;

- (BatPBFieldOptions*) build;
- (BatPBFieldOptions*) buildPartial;

- (BatPBFieldOptions_Builder*) mergeFrom:(BatPBFieldOptions*) other;
- (BatPBFieldOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBFieldOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCtype;
- (PBFieldOptions_CType) ctype;
- (BatPBFieldOptions_Builder*) setCtype:(PBFieldOptions_CType) value;
- (BatPBFieldOptions_Builder*) clearCtype;

- (BOOL) hasPacked;
- (BOOL) packed;
- (BatPBFieldOptions_Builder*) setPacked:(BOOL) value;
- (BatPBFieldOptions_Builder*) clearPacked;

- (BOOL) hasDeprecated;
- (BOOL) deprecated;
- (BatPBFieldOptions_Builder*) setDeprecated:(BOOL) value;
- (BatPBFieldOptions_Builder*) clearDeprecated;

- (BOOL) hasExperimentalMapKey;
- (NSString*) experimentalMapKey;
- (BatPBFieldOptions_Builder*) setExperimentalMapKey:(NSString*) value;
- (BatPBFieldOptions_Builder*) clearExperimentalMapKey;

- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (BatPBFieldOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(BatPBUninterpretedOption*) value;
- (BatPBFieldOptions_Builder*) addUninterpretedOption:(BatPBUninterpretedOption*) value;
- (BatPBFieldOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (BatPBFieldOptions_Builder*) clearUninterpretedOptionList;
@end

@interface BatPBEnumOptions : BatPBExtendableMessage {
@private
  NSMutableArray* mutableUninterpretedOptionList;
}
- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (BatPBEnumOptions*) defaultInstance;
- (BatPBEnumOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBEnumOptions_Builder*) builder;
+ (BatPBEnumOptions_Builder*) builder;
+ (BatPBEnumOptions_Builder*) builderWithPrototype:(BatPBEnumOptions*) prototype;

+ (BatPBEnumOptions*) parseFromData:(NSData*) data;
+ (BatPBEnumOptions*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBEnumOptions*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBEnumOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBEnumOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBEnumOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBEnumOptions_Builder : BatPBExtendableMessage_Builder {
@private
  BatPBEnumOptions* result;
}

- (BatPBEnumOptions*) defaultInstance;

- (BatPBEnumOptions_Builder*) clear;
- (BatPBEnumOptions_Builder*) clone;

- (BatPBEnumOptions*) build;
- (BatPBEnumOptions*) buildPartial;

- (BatPBEnumOptions_Builder*) mergeFrom:(BatPBEnumOptions*) other;
- (BatPBEnumOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBEnumOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (BatPBEnumOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(BatPBUninterpretedOption*) value;
- (BatPBEnumOptions_Builder*) addUninterpretedOption:(BatPBUninterpretedOption*) value;
- (BatPBEnumOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (BatPBEnumOptions_Builder*) clearUninterpretedOptionList;
@end

@interface BatPBEnumValueOptions : BatPBExtendableMessage {
@private
  NSMutableArray* mutableUninterpretedOptionList;
}
- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (BatPBEnumValueOptions*) defaultInstance;
- (BatPBEnumValueOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBEnumValueOptions_Builder*) builder;
+ (BatPBEnumValueOptions_Builder*) builder;
+ (BatPBEnumValueOptions_Builder*) builderWithPrototype:(BatPBEnumValueOptions*) prototype;

+ (BatPBEnumValueOptions*) parseFromData:(NSData*) data;
+ (BatPBEnumValueOptions*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBEnumValueOptions*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBEnumValueOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBEnumValueOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBEnumValueOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBEnumValueOptions_Builder : BatPBExtendableMessage_Builder {
@private
  BatPBEnumValueOptions* result;
}

- (BatPBEnumValueOptions*) defaultInstance;

- (BatPBEnumValueOptions_Builder*) clear;
- (BatPBEnumValueOptions_Builder*) clone;

- (BatPBEnumValueOptions*) build;
- (BatPBEnumValueOptions*) buildPartial;

- (BatPBEnumValueOptions_Builder*) mergeFrom:(BatPBEnumValueOptions*) other;
- (BatPBEnumValueOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBEnumValueOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (BatPBEnumValueOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(BatPBUninterpretedOption*) value;
- (BatPBEnumValueOptions_Builder*) addUninterpretedOption:(BatPBUninterpretedOption*) value;
- (BatPBEnumValueOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (BatPBEnumValueOptions_Builder*) clearUninterpretedOptionList;
@end

@interface BatPBServiceOptions : BatPBExtendableMessage {
@private
  NSMutableArray* mutableUninterpretedOptionList;
}
- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (BatPBServiceOptions*) defaultInstance;
- (BatPBServiceOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBServiceOptions_Builder*) builder;
+ (BatPBServiceOptions_Builder*) builder;
+ (BatPBServiceOptions_Builder*) builderWithPrototype:(BatPBServiceOptions*) prototype;

+ (BatPBServiceOptions*) parseFromData:(NSData*) data;
+ (BatPBServiceOptions*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBServiceOptions*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBServiceOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBServiceOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBServiceOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBServiceOptions_Builder : BatPBExtendableMessage_Builder {
@private
  BatPBServiceOptions* result;
}

- (BatPBServiceOptions*) defaultInstance;

- (BatPBServiceOptions_Builder*) clear;
- (BatPBServiceOptions_Builder*) clone;

- (BatPBServiceOptions*) build;
- (BatPBServiceOptions*) buildPartial;

- (BatPBServiceOptions_Builder*) mergeFrom:(BatPBServiceOptions*) other;
- (BatPBServiceOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBServiceOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (BatPBServiceOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(BatPBUninterpretedOption*) value;
- (BatPBServiceOptions_Builder*) addUninterpretedOption:(BatPBUninterpretedOption*) value;
- (BatPBServiceOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (BatPBServiceOptions_Builder*) clearUninterpretedOptionList;
@end

@interface BatPBMethodOptions : BatPBExtendableMessage {
@private
  NSMutableArray* mutableUninterpretedOptionList;
}
- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;

+ (BatPBMethodOptions*) defaultInstance;
- (BatPBMethodOptions*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBMethodOptions_Builder*) builder;
+ (BatPBMethodOptions_Builder*) builder;
+ (BatPBMethodOptions_Builder*) builderWithPrototype:(BatPBMethodOptions*) prototype;

+ (BatPBMethodOptions*) parseFromData:(NSData*) data;
+ (BatPBMethodOptions*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBMethodOptions*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBMethodOptions*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBMethodOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBMethodOptions*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBMethodOptions_Builder : BatPBExtendableMessage_Builder {
@private
  BatPBMethodOptions* result;
}

- (BatPBMethodOptions*) defaultInstance;

- (BatPBMethodOptions_Builder*) clear;
- (BatPBMethodOptions_Builder*) clone;

- (BatPBMethodOptions*) build;
- (BatPBMethodOptions*) buildPartial;

- (BatPBMethodOptions_Builder*) mergeFrom:(BatPBMethodOptions*) other;
- (BatPBMethodOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBMethodOptions_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (NSArray*) uninterpretedOptionList;
- (BatPBUninterpretedOption*) uninterpretedOptionAtIndex:(int32_t) index;
- (BatPBMethodOptions_Builder*) replaceUninterpretedOptionAtIndex:(int32_t) index with:(BatPBUninterpretedOption*) value;
- (BatPBMethodOptions_Builder*) addUninterpretedOption:(BatPBUninterpretedOption*) value;
- (BatPBMethodOptions_Builder*) addAllUninterpretedOption:(NSArray*) values;
- (BatPBMethodOptions_Builder*) clearUninterpretedOptionList;
@end

@interface BatPBUninterpretedOption : BatPBGeneratedMessage {
@private
  BOOL hasDoubleValue_:1;
  BOOL hasNegativeIntValue_:1;
  BOOL hasPositiveIntValue_:1;
  BOOL hasIdentifierValue_:1;
  BOOL hasStringValue_:1;
  Float64 doubleValue;
  int64_t negativeIntValue;
  int64_t positiveIntValue;
  NSString* identifierValue;
  NSData* stringValue;
  NSMutableArray* mutableNameList;
}
- (BOOL) hasIdentifierValue;
- (BOOL) hasPositiveIntValue;
- (BOOL) hasNegativeIntValue;
- (BOOL) hasDoubleValue;
- (BOOL) hasStringValue;
@property (readonly, retain) NSString* identifierValue;
@property (readonly) int64_t positiveIntValue;
@property (readonly) int64_t negativeIntValue;
@property (readonly) Float64 doubleValue;
@property (readonly, retain) NSData* stringValue;
- (NSArray*) nameList;
- (BatPBUninterpretedOption_NamePart*) nameAtIndex:(int32_t) index;

+ (BatPBUninterpretedOption*) defaultInstance;
- (BatPBUninterpretedOption*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBUninterpretedOption_Builder*) builder;
+ (BatPBUninterpretedOption_Builder*) builder;
+ (BatPBUninterpretedOption_Builder*) builderWithPrototype:(BatPBUninterpretedOption*) prototype;

+ (BatPBUninterpretedOption*) parseFromData:(NSData*) data;
+ (BatPBUninterpretedOption*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBUninterpretedOption*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBUninterpretedOption*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBUninterpretedOption*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBUninterpretedOption*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBUninterpretedOption_NamePart : BatPBGeneratedMessage {
@private
  BOOL hasIsExtension_:1;
  BOOL hasNamePart_:1;
  BOOL isExtension_:1;
  NSString* namePart;
}
- (BOOL) hasNamePart;
- (BOOL) hasIsExtension;
@property (readonly, retain) NSString* namePart;
- (BOOL) isExtension;

+ (BatPBUninterpretedOption_NamePart*) defaultInstance;
- (BatPBUninterpretedOption_NamePart*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(BatPBCodedOutputStream*) output;
- (BatPBUninterpretedOption_NamePart_Builder*) builder;
+ (BatPBUninterpretedOption_NamePart_Builder*) builder;
+ (BatPBUninterpretedOption_NamePart_Builder*) builderWithPrototype:(BatPBUninterpretedOption_NamePart*) prototype;

+ (BatPBUninterpretedOption_NamePart*) parseFromData:(NSData*) data;
+ (BatPBUninterpretedOption_NamePart*) parseFromData:(NSData*) data extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBUninterpretedOption_NamePart*) parseFromInputStream:(NSInputStream*) input;
+ (BatPBUninterpretedOption_NamePart*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
+ (BatPBUninterpretedOption_NamePart*) parseFromCodedInputStream:(BatPBCodedInputStream*) input;
+ (BatPBUninterpretedOption_NamePart*) parseFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;
@end

@interface BatPBUninterpretedOption_NamePart_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBUninterpretedOption_NamePart* result;
}

- (BatPBUninterpretedOption_NamePart*) defaultInstance;

- (BatPBUninterpretedOption_NamePart_Builder*) clear;
- (BatPBUninterpretedOption_NamePart_Builder*) clone;

- (BatPBUninterpretedOption_NamePart*) build;
- (BatPBUninterpretedOption_NamePart*) buildPartial;

- (BatPBUninterpretedOption_NamePart_Builder*) mergeFrom:(BatPBUninterpretedOption_NamePart*) other;
- (BatPBUninterpretedOption_NamePart_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBUninterpretedOption_NamePart_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNamePart;
- (NSString*) namePart;
- (BatPBUninterpretedOption_NamePart_Builder*) setNamePart:(NSString*) value;
- (BatPBUninterpretedOption_NamePart_Builder*) clearNamePart;

- (BOOL) hasIsExtension;
- (BOOL) isExtension;
- (BatPBUninterpretedOption_NamePart_Builder*) setIsExtension:(BOOL) value;
- (BatPBUninterpretedOption_NamePart_Builder*) clearIsExtension;
@end

@interface BatPBUninterpretedOption_Builder : BatPBGeneratedMessage_Builder {
@private
  BatPBUninterpretedOption* result;
}

- (BatPBUninterpretedOption*) defaultInstance;

- (BatPBUninterpretedOption_Builder*) clear;
- (BatPBUninterpretedOption_Builder*) clone;

- (BatPBUninterpretedOption*) build;
- (BatPBUninterpretedOption*) buildPartial;

- (BatPBUninterpretedOption_Builder*) mergeFrom:(BatPBUninterpretedOption*) other;
- (BatPBUninterpretedOption_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input;
- (BatPBUninterpretedOption_Builder*) mergeFromCodedInputStream:(BatPBCodedInputStream*) input extensionRegistry:(BatPBExtensionRegistry*) extensionRegistry;

- (NSArray*) nameList;
- (BatPBUninterpretedOption_NamePart*) nameAtIndex:(int32_t) index;
- (BatPBUninterpretedOption_Builder*) replaceNameAtIndex:(int32_t) index with:(BatPBUninterpretedOption_NamePart*) value;
- (BatPBUninterpretedOption_Builder*) addName:(BatPBUninterpretedOption_NamePart*) value;
- (BatPBUninterpretedOption_Builder*) addAllName:(NSArray*) values;
- (BatPBUninterpretedOption_Builder*) clearNameList;

- (BOOL) hasIdentifierValue;
- (NSString*) identifierValue;
- (BatPBUninterpretedOption_Builder*) setIdentifierValue:(NSString*) value;
- (BatPBUninterpretedOption_Builder*) clearIdentifierValue;

- (BOOL) hasPositiveIntValue;
- (int64_t) positiveIntValue;
- (BatPBUninterpretedOption_Builder*) setPositiveIntValue:(int64_t) value;
- (BatPBUninterpretedOption_Builder*) clearPositiveIntValue;

- (BOOL) hasNegativeIntValue;
- (int64_t) negativeIntValue;
- (BatPBUninterpretedOption_Builder*) setNegativeIntValue:(int64_t) value;
- (BatPBUninterpretedOption_Builder*) clearNegativeIntValue;

- (BOOL) hasDoubleValue;
- (Float64) doubleValue;
- (BatPBUninterpretedOption_Builder*) setDoubleValue:(Float64) value;
- (BatPBUninterpretedOption_Builder*) clearDoubleValue;

- (BOOL) hasStringValue;
- (NSData*) stringValue;
- (BatPBUninterpretedOption_Builder*) setStringValue:(NSData*) value;
- (BatPBUninterpretedOption_Builder*) clearStringValue;
@end

